### ISSUE TITLE
Explaination/Doc of params in API V3 and scenario request.

### ISSUE THREAD

**Issue by hubert-associates** [NREL/REopt.jl#137]
Hi. We are looking at both the py and jl V3 API (still under dev, I am aware). So, just wondering we are missing the place where these Inputs are explained a bit? https://nrel.github.io/REopt.jl/dev/reopt/inputs/ The /outputs are explained somewhat better. Or is the code currently the only place. If so, I'm still wondering what tou_  means and what a blended rate is :-) 

I'm still working on a scenario where a large home site has roof-space, existing pellets heating, and a utility feed-in-tariff of 6cents. We want to optimize the scenario to assess the potential benefit of storage or flexibleHVAC. I am getting strange results because, I am convinced, am not understanding the params yet (see above). Any tips appreciated.

Regards

**Comment by adfarth** [comment]
Hello! We are still working on updating documentation for the inputs in REopt.jl, but you could take a look at the job/models.py file in REopt_API. The inputs here align with those in REopt.jl: https://github.com/NREL/REopt_API/blob/master/job/models.py

**Comment by Bill-Becker** [comment]
This is our current mapping of V2 -> V3: 
https://github.com/NREL/REopt-API-Analysis/wiki/Legacy-REO-to-v3-REopt-API-inputs-mapping.

We are also working on finishing this up and improving the formatting of it for easier use.
