### ISSUE TITLE
Update naming convention for dispatch outputs

### ISSUE THREAD

**Issue by lixiangk1** [NREL/REopt.jl#139]
Is "year_one" in the tech time series output names a misnomer? Dispatches are calculated for an average year and could be confusing.

e.g., For PV `year_one_to_load_series_kw` + `year_one_to_battery_series_kw` + `year_one_curtailed_production_series_kw` + `year_one_to_grid_series_kw` = `average_annual_energy_produced_kwh` and not `year_one_energy_produced_kwh`

**Comment by adfarth** [comment]
I had the same thought and chatted about this with Nick. He had a reason for keeping it as "year_one", which I can't recall. I'll look through my notes and see if I can find his thoughts.
