### ISSUE TITLE
Issues running "test/scenarios/outage.json"

### ISSUE THREAD

**Issue by JorgeLOrtiz** [NREL/REopt.jl#234]
I have not been able to run the REopt Julia package locally for any outage.json scenarios (including gen_pv_stor.json and gen_pv_wind_stor.json). It doesn't seem to work with the HIGHS solver (Error) or Cbc (slow, not a solution found after 972873.03 seconds). Also, I tried with the Community License of Xpress (free version), but it shows the following error:

"Xpress.XpressError(120, \"Xpress internal error:\\n\\n120 Error: Problem has too many rows and columns. The maximum is 5000.\\n\")"

Is there any specific FICO Xpress Optimization Option or Cplex C API required to run the mentioned test scenarios properly?

Thank you

**Comment by zolanaj** [comment]
Sorry for the delayed response; outages are now compatible with HiGHS, due to a recent workaround that implements indicator constraints as big-M's here: https://github.com/NREL/REopt.jl/pull/368
