### ISSUE TITLE
Force dispatch of specific heating techs to heat loads

### ISSUE THREAD

**Issue by zolanaj** [NREL/REopt.jl#335]
First mentioned in the comments by @Bill-Becker to https://github.com/NREL/REopt.jl/pull/294: this may be suboptimal compared to allowing all technologies to freely meet compatible loads, but may be a desired feature due to infrastructure constraints (such as using the electric heater to fulfill all of the process heat).

**Comment by zolanaj** [comment]
@Bill-Becker the `force_into_system` feature in ASHP added in https://github.com/NREL/REopt.jl/pull/372 does address this for ASHP and I believe we have something analogous for GHP.  Do we want to add that attribute to the other heating technologies too?

**Comment by Bill-Becker** [comment]
> @Bill-Becker the `force_into_system` feature in ASHP added in #372 does address this for ASHP and I believe we have something analogous for GHP. Do we want to add that attribute to the other heating technologies too?

Agreed!
