### ISSUE TITLE
Handle time_steps_per_hour > 1

### ISSUE THREAD

**Issue by adfarth** [NREL/REopt.jl#48]

**Comment by NLaws** [comment]
@adfarth what is the motivation for this issue? this is a huge task and raises a lot of questions, especially how we would determine the electric tariff.

**Comment by adfarth** [comment]
@NLaws In general don't we want to be able to model down to 15-minute intervals? It seemed like this was an intended capability (and one we currently have in the API), but I was getting errors when trying to use sub-hourly loads. You may have fixed the issues in 7d7bc2295a033d308b4296f179c3d7798dc10032. I have not checked since then

**Comment by NLaws** [comment]
oh sorry I interpreted this incorrectly as handle time_steps_per_hour < 1. As far as I know 15 or 30 minute models can be run and I have run many 15 minute storage models.

**Comment by adfarth** [comment]
@NLaws it was an issue with generator scenarios. I addressed it in this PR https://github.com/NREL/REopt.jl/pull/71
