### ISSUE TITLE
Add electric heater to REopt.jl

### ISSUE THREAD

**Issue by zolanaj** [NREL/REopt.jl#64]
Background: There is a desire to introduce an electric heater into REopt to address thermal loads because in its simplest form, it could be a relatively light lift, and it may represent an opportunity to compare various options against the GHP developed by Bill (and allow for electrification of all loads, which might be desirable when trying to obtain a zero-carbon solution).  A lightly organized menu of options follows (all would have an electric COP but not a fuel efficiency): 

1. Resistive electric heater: fixed COP of ~1
2. Air-sourced heat pump: COP >1, could be a temperature-dependent COP that we source from existing database, provide cooling and heating (simultaneously if distributed, like GHP) with a single capital cost and common rating?  
3. Electric hot water heater: COP TBD, addresses hot water load.  We might have to separate the heating load in REopt, with each heating technology addressing hot water only (e.g., electric hot water heater), space heating only (e.g., heat pump), or both (e.g., boiler, hot TES, or maybe an appropriately rated heat pump).

Note: If we separate the hot water and space heating loads, do we want another high-temperature heat load for commercial or light industrial use?  This could advertise the benefits of CHP.

**Comment by Bill-Becker** [comment]
@zolanaj should we tag the open PR with this issue?

**Comment by zolanaj** [comment]
> @zolanaj should we tag the open PR with this issue?

@Bill-Becker done!  https://github.com/NREL/REopt.jl/pull/256
