### ISSUE TITLE
Update AVERT data and regions to latest version

### ISSUE THREAD

**Issue by adfarth** [NREL/REopt.jl#65]

**Comment by NLaws** [comment]
@adfarth looks like this issues is closed?

somewhat related: is the results `ElectricUtility.year_one_emissions_tonnes_XXX` the same as `Site. year_one_emissions_from_elec_grid_tonnes_XXX`? (I was thinking of adding an issue to better document the emissions outputs.)

**Comment by adfarth** [comment]
> @adfarth looks like this issue is closed?
> 
> somewhat related: is the results `ElectricUtility.year_one_emissions_tonnes_XXX` the same as `Site. year_one_emissions_from_elec_grid_tonnes_XXX`? (I was thinking of adding an issue to better document the emissions outputs.)

Yes, this issue is closed with the merging of PR #100. We now use [AVERT v3.2](https://www.epa.gov/avert/download-avert) (2021 data) if no emissions data are provided. 

Regarding emissions outputs, I think we no longer report `Site. year_one_emissions_from_elec_grid_tonnes_XXX` (although this is still included in results.jl, by mistake I believe--am checking with Hallie) and the yr1 electric grid emissions are only reported as `ElectricUtility.year_one_emissions_tonnes_XXX`. Please feel free to open an issue to better document the emissions outputs--we should definitely do that!

**Comment by hdunham** [comment]
> > @adfarth looks like this issue is closed?
> > somewhat related: is the results `ElectricUtility.year_one_emissions_tonnes_XXX` the same as `Site. year_one_emissions_from_elec_grid_tonnes_XXX`? (I was thinking of adding an issue to better document the emissions outputs.)
> 
> Yes, this issue is closed with the merging of PR #100. We now use [AVERT v3.2](https://www.epa.gov/avert/download-avert) (2021 data) if no emissions data are provided.
> 
> Regarding emissions outputs, I think we no longer report `Site. year_one_emissions_from_elec_grid_tonnes_XXX` (although this is still included in results.jl, by mistake I believe--am checking with Hallie) and the yr1 electric grid emissions are only reported as `ElectricUtility.year_one_emissions_tonnes_XXX`. Please feel free to open an issue to better document the emissions outputs--we should definitely do that!

Yes, I removed grid emissions from site because I didn't think it belonged there. It's only in ElectricUtility now. I did forget to remove it from the list of BAU outputs in results.jl. This doesn't cause any error because of the check on line 195, but should be removed eventually.
