### ISSUE TITLE
Account for outage_is_major_event

### ISSUE THREAD

**Issue by adfarth** [NREL/REopt.jl#67]

**Comment by adfarth** [comment]
We no longer want to do this. @hdunham to replace this task with updates to existing multi-/probabilistic outage modeling (in Julia & API) -- right?

**Comment by hdunham** [comment]
Yes, and there is already an issue for adding multi outage modeling to the API that I have assigned to myself. All that needs to be done in the Julia package now is delete the TODO comment about accounting for outage_is_major_event.
