### ISSUE TITLE
Refactor "pct" and "_rate" input/variable naming in REopt.jl

### ISSUE THREAD

**Issue by Bill-Becker** [NREL/REopt.jl#99]
- Change "pct" to "rate_fraction" for "discount" and "excalation", etc (financial terms)
- Change "pct" to "fraction" for inputs such as "min_soc", "min_turndown_", etc
- Remove "annual" or "per_year" for "rate" terms, even though that is the basis, to reduce verbosity. Add that all financial "rates" are annual basis (as opposed to "monthly" or some other time period, which is much less common)

**Comment by Bill-Becker** [comment]
@adfarth can you confirm this is completed (I think so), and close it if so.

**Comment by adfarth** [comment]
yes! Closed with https://github.com/NREL/REopt.jl/pull/124
